---
name: JokeOfTheWeekPM4
version: 0.0.1
main: skyss0fly\JokeOfTheWeekPM4\
api: 4.5.2
src-namespace-prefix: skyss0fly\JokeOfTheWeekPM4\src

commands:
     jotw:
     description: Tell a funny Joke!
     aliases: 
     - Joke
     permission: jotw.command
permissions:
 jotw.command:
 description: Permission for /jotw
 default: true
...
