--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/skyss0fly/JokeOfTheWeekPM4
build-by-default: true
branches:
- main
projects:
  JokeOfTheWeekPM4:
    path: JokeOfTheWeekPM4/
    icon: JokeOfTheWeekPM4/blob/main/icon.png
...
