--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/skyss0fly/JokeOfTheWeekPM4
build-by-default: true
branches:
- main
projects:
  JokeOfTheWeekPM4:
    path: ""
    libs:
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
...
