---
name: JokeOfTheWeekPM4
version: 1.2.1
main: skyss0fly\JokeOfTheWeekPM4\Main
api: 4.17.0
src-namespace-prefix: skyss0fly\JokeOfTheWeekPM4

commands:
  joke:
    permission: JokeOfTheWeekPM4.command
    description: Tells a joke! [COMMAND DISABLED!].

permissions:
  JokeOfTheWeekPM4.command:
    default: false
...
